<Project>
	<PropertyGroup>
		<BuildNumber Condition="'$(BuildNumber)' == ''">0.0</BuildNumber>
		<MajorVersion>9.58</MajorVersion>
		<Version>$(MajorVersion).$(BuildNumber)</Version>
	</PropertyGroup>
	<PropertyGroup>
		<Publisher Condition="'$(Publisher)' == ''">CN=OHMS</Publisher>
		<PublisherDisplayName Condition="'$(PublisherDisplayName)' == ''">OHMS</PublisherDisplayName>
	</PropertyGroup>
	<PropertyGroup>
		<CommerceSdkPackagesVersion>[9.58.*-*,9.59)</CommerceSdkPackagesVersion>
		<CommercePosPackagesVersion>[9.58.*-*,9.59)</CommercePosPackagesVersion>
		<CommerceChannelPackagesVersion>[9.58.*-*,9.59)</CommerceChannelPackagesVersion>
		<CommerceHwsPackagesVersion>[9.58.*-*,9.59)</CommerceHwsPackagesVersion>
		<CommerceToolsPackagesVersion>[10.38.*-*,10.39)</CommerceToolsPackagesVersion>
		<CommercePaymentsPackagesVersion>[10.54.*-*,10.55)</CommercePaymentsPackagesVersion>
	</PropertyGroup>
</Project>